#!/bin/sh
  launch_temporary_container(){
    case $1 in
    -i|--img) #image_name
      : ${2:?-i\|--image option needs an argument!};
      app_name=${app_image:-`list_images | grep $2 | head -1`};
      test -z "${app_name}" && throw unknown container image with $2
      shift 2;
    esac
    setvar cosh_container ${this:-null}_`genseed 8`
    ${SUDOING:+sudo} docker run --name `getvar cosh_container` \
      -dt \
      --rm \
      -u `getvar cosh_user` \
      --network `getvar cosh_network` \
      -e DISPLAY=:0 \
      -e LANGUAGE=$LANGUAGE \
      -e LANG=$LANG \
      -e LC_ALL=$LC_ALL \
      -e XMODIFIERS=$XMODIFIERS \
      -e GTK_IM_MODULE=$GTK_IM_MODULE \
      -e QT_IM_MODULE=$QT_IM_MODULE \
      $vol_args \
      -v /dev/dri:/dev/dri \
      -v /dev/shm:/dev/shm \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      ${app_name:-$COSH_DEFAULT_APP_IMAGE} \
      $@
    unset vol_args; 
    exit
  }
