#!/bin/sh
  launch_temporary_container(){
    case $1 in
    -i|--img) #image_name
      : ${2:?-i\|--image option needs an argument!};
      app_image=`docker images | grep -E "^${login_name:-coshapp}/[[:alnum:]]*$2" | tr " "  : | sed -r -e s/:\+/:/g -e 's/^([^:]+:[^:]+).+/\1/g' | grep latest | head -1`
      shift 2;
    esac
    setvar cosh_container cosh_`genseed 8`
    docker run --name `getvar cosh_container` \
      -dt \
      --rm \
      -u `getvar cosh_user` \
      -e DISPLAY=$DISPLAY \
      -e LANGUAGE=$LANGUAGE \
      -e LANG=$LANG \
      -e LC_ALL=$LC_ALL \
      -e XMODIFIERS=$XMODIFIERS \
      -e GTK_IM_MODULE=$GTK_IM_MODULE \
      -e QT_IM_MODULE=$QT_IM_MODULE \
      -v /dev/dri:/dev/dri \
      -v /dev/shm:/dev/shm \
      -v /tmp/.X11-unix:/tmp/.X11-unix \
      ${app_image:-$default_app_image} \
      sh -c "while :; do sleep 100000; done"
    set_cmd $@; execute;
  }
