#!/bin/sh
# list container images

list_images(){
  list_image_name_full(){ ${SUDOING:+sudo} docker images | grep -E "^${COSH_APP_PREPEND:?stackname not defined}/.*$1.*"; }
  list_image_name_short(){ list_image_name_full $1 | awk '{print $1 ":" $2}'; }

  case "$1" in --full|-f) list_image_name_full $2;; *) list_image_name_short $@ ;; esac
}

