#!/bin/sh
# set network assigned to container

chk_set_network(){
  : ${1:?at least one argument needed for -n option, abort!}
}
set_network(){
  chk_set_network $2
  setvar network "--network $2"
  shiftstack 2 $@
}
