#!/bin/sh
chk_set_container(){
  test -z "${1}" && throw "at least one argument needed for -c option, abort!";
}
set_container(){
  chk_set_container $2;
  setvar cosh_container $2;
  shiftstack 2 $@
}
