#!/bin/sh
# set shell for the execution inside the container
execute_in_container_shell(){
  ${SUDOING:+sudo} docker exec \
    -u $(getvar cosh_user) \
    -it $(get_target_container) \
    /bin/sh
}

set_shell(){
  execute_in_container(){ execute_in_container_shell; }
}

