#!/bin/sh
# set cosh script for the execution
# shebang (#!/path/to/cosh -f) also supported

set_file(){
  sanitize "$*";
  test -f "$1" || return 1
  setvar exec_file $1

  parseargs(){ :; }

  execute(){
      ${SUDOING:+sudo} docker exec \
        -u $(getvar cosh_user) \
	-i $(get_target_container) \
	/bin/sh < $(getvar exec_file)
  }

  shiftstack 1 $@

}
