#!/bin/sh
# set standard input listener for the container

set_stdin(){
  test -t 0 && return 1
  parseargs(){
    setvar cmd "${*:-/bin/sh}"
  }
  execute(){
      test -z "$ONETIME" && setvar subcom exec
      test ! -z "$ONETIME" && {
        setvar subcom run
      }
      ${SUDOING:+sudo} docker \
        $(getvar subcom) \
        -u $(getvar cosh_user) \
        -i $(get_target_container) \
        $(getvar cosh_app_image 2> /dev/null) \
        $(getvar cmd)
  }
  shiftstack 0 $@
}
